return {
    armuwafus = {
        name = "Underwater Advanced Fusion Reactor",
        description = "Advanced fusion reactor for seabed construction",
        buildangle = 4096,
        buildpic = "ARMAFUS.DDS",
        buildtime = 312500,
        canrepeat = false,
        collisionvolumeoffsets = "0 0 0",
        collisionvolumescales = "96 96 96",
        collisionvolumetype = "Box",
        corpse = "DEAD",
        energycost = 69000,
        energymake = 3000,
        energystorage = 9000,
        explodeas = "customfusionexplo",
        footprintx = 6,
        footprintz = 6,
        health = 8300,
        maxacc = 0,
        maxdec = 0,
        maxslope = 13,
        metalcost = 9700,
        minwaterdepth = 25,
        objectname = "Units/armuwafus.s3o",
        script = "Units/ARMAFUS.cob",
        seismicsignature = 0,
        selfdestructas = "advancedFusionExplosionSelfd",
        sightdistance = 273,
        yardmap = "oooooooooooooooooooooooooooooooooooo",
        customparams = {
            buildinggrounddecaldecayspeed = 30,
            buildinggrounddecalsizex = 9,
            buildinggrounddecalsizey = 9,
            buildinggrounddecaltype = "decals/armafus_aoplane.dds",
            model_author = "Cremuss; underwater variant by RandomGuy",
            normaltex = "unittextures/Arm_normal.dds",
            removestop = true,
            removewait = true,
            subfolder = "ArmBuildings/SeaEconomy",
            techlevel = 2,
            unitgroup = "energy",
            restrictions_inclusion = "_nofusion_",
            usebuildinggrounddecal = true,
        },
        featuredefs = {
            dead = {
                blocking = true,
                category = "corpses",
                collisionvolumeoffsets = "0 0 0",
                collisionvolumescales = "96 96 96",
                collisionvolumetype = "Box",
                damage = 16290,
                featuredead = "HEAP",
                footprintx = 5,
                footprintz = 4,
                height = 40,
                metal = 6441,
                object = "Units/armafus_dead.s3o",
                reclaimable = true,
            },
            heap = {
                blocking = false,
                category = "heaps",
                collisionvolumescales = "96.0 14.0 6.0",
                collisionvolumetype = "box",
                damage = 8145,
                footprintx = 4,
                footprintz = 4,
                height = 4,
                metal = 2576,
                object = "Units/arm4X4A.s3o",
                reclaimable = true,
                resurrectable = 0,
            },
        },
        sounds = {
            canceldestruct = "cancel2",
            underattack = "warning1",
            count = {
                [1] = "count6", [2] = "count5", [3] = "count4",
                [4] = "count3", [5] = "count2", [6] = "count1",
            },
            select = { [1] = "fusion1" },
        },
    },

    coruwafus = {
        name = "Underwater Advanced Fusion Reactor",
        description = "Advanced fusion reactor for seabed construction",
        buildangle = 4096,
        buildpic = "CORAFUS.DDS",
        buildtime = 329200,
        canrepeat = false,
        collisionvolumeoffsets = "0 0 0",
        collisionvolumescales = "84 95 84",
        collisionvolumetype = "CylY",
        corpse = "DEAD",
        energycost = 48000,
        energymake = 3000,
        energystorage = 9000,
        explodeas = "customfusionexplo",
        footprintx = 6,
        footprintz = 6,
        health = 9800,
        maxacc = 0,
        maxdec = 0,
        maxslope = 13,
        metalcost = 9700,
        minwaterdepth = 25,
        objectname = "Units/coruwafus.s3o",
        script = "Units/CORAFUS.cob",
        seismicsignature = 0,
        selfdestructas = "advancedFusionExplosionSelfd",
        sightdistance = 273,
        yardmap = "oooooooooooooooooooooooooooooooooooo",
        customparams = {
            buildinggrounddecaldecayspeed = 30,
            buildinggrounddecalsizex = 9,
            buildinggrounddecalsizey = 9,
            buildinggrounddecaltype = "decals/corafus_aoplane.dds",
            model_author = "Cremuss; underwater variant by RandomGuy",
            normaltex = "unittextures/cor_normal.dds",
            removestop = true,
            removewait = true,
            subfolder = "CorBuildings/SeaEconomy",
            techlevel = 2,
            unitgroup = "energy",
            restrictions_inclusion = "_nofusion_",
            usebuildinggrounddecal = true,
        },
        featuredefs = {
            dead = {
                blocking = true,
                category = "corpses",
                collisionvolumeoffsets = "-5.1672668457 -0.194635522461 -0.799919128418",
                collisionvolumescales = "114.264892578 89.6709289551 97.8311309814",
                collisionvolumetype = "Box",
                damage = 17100,
                featuredead = "HEAP",
                footprintx = 5,
                footprintz = 4,
                height = 20,
                metal = 6440,
                object = "Units/corafus_dead.s3o",
                reclaimable = true,
            },
            heap = {
                blocking = false,
                category = "heaps",
                collisionvolumescales = "85.0 14.0 6.0",
                collisionvolumetype = "cylY",
                damage = 8550,
                footprintx = 5,
                footprintz = 4,
                height = 4,
                metal = 2576,
                object = "Units/cor4X4A.s3o",
                reclaimable = true,
                resurrectable = 0,
            },
        },
        sounds = {
            canceldestruct = "cancel2",
            underattack = "warning1",
            count = {
                [1] = "count6", [2] = "count5", [3] = "count4",
                [4] = "count3", [5] = "count2", [6] = "count1",
            },
            select = { [1] = "fusion2" },
        },
    },

    leguwafus = {
        name = "Underwater Advanced Fusion Reactor",
        description = "Advanced fusion reactor for seabed construction",
        buildangle = 4096,
        buildpic = "LEGAFUS.DDS",
        buildtime = 340000,
        canrepeat = false,
        collisionvolumeoffsets = "0 0 0",
        collisionvolumescales = "111 103 110",
        collisionvolumetype = "Box",
        corpse = "DEAD",
        energycost = 69000,
        energymake = 3300,
        energystorage = 9000,
        explodeas = "customfusionexplo",
        footprintx = 6,
        footprintz = 6,
        health = 9800,
        maxacc = 0,
        maxdec = 0,
        maxslope = 13,
        metalcost = 10500,
        minwaterdepth = 25,
        objectname = "Units/leguwafus.s3o",
        script = "Units/LEGAFUS.cob",
        seismicsignature = 0,
        selfdestructas = "advancedFusionExplosionSelfd",
        sightdistance = 273,
        yardmap = "oooooooooooooooooooooooooooooooooooo",
        customparams = {
            buildinggrounddecaldecayspeed = 30,
            buildinggrounddecalsizex = 10,
            buildinggrounddecalsizey = 10,
            buildinggrounddecaltype = "decals/legafus_aoplane.dds",
            model_author = "Protar; underwater variant by RandomGuy",
            normaltex = "unittextures/leg_normal.dds",
            removestop = true,
            removewait = true,
            subfolder = "Legion/SeaEconomy/T2",
            techlevel = 2,
            unitgroup = "energy",
            restrictions_inclusion = "_nofusion_",
            usebuildinggrounddecal = true,
        },
        featuredefs = {
            dead = {
                blocking = true,
                category = "corpses",
                collisionvolumeoffsets = "0 0 0",
                collisionvolumescales = "111 103 110",
                collisionvolumetype = "Box",
                damage = 16290,
                featuredead = "HEAP",
                footprintx = 6,
                footprintz = 6,
                height = 40,
                metal = 6441,
                object = "Units/legafus_dead.s3o",
                reclaimable = true,
            },
            heap = {
                blocking = false,
                category = "heaps",
                collisionvolumescales = "96.0 14.0 6.0",
                collisionvolumetype = "box",
                damage = 8145,
                footprintx = 6,
                footprintz = 6,
                height = 4,
                metal = 2576,
                object = "Units/arm4X4A.s3o",
                reclaimable = true,
                resurrectable = 0,
            },
        },
        sounds = {
            canceldestruct = "cancel2",
            underattack = "warning1",
            count = {
                [1] = "count6", [2] = "count5", [3] = "count4",
                [4] = "count3", [5] = "count2", [6] = "count1",
            },
            select = { [1] = "fusion1" },
        },
    },
}
